  open Formula
let getstr = function
| ACCEPT  -> "ACCEPT"
| AMPERSAND  -> "AMPERSAND"
| AT  -> "AT"
| BACKQUOTE  -> "BACKQUOTE"
| BACKSLASH  -> "BACKSLASH"
| CARET  -> "CARET"
| COLON  -> "COLON"
| COMMA  -> "COMMA"
| CONS1  _ -> "CONS1"
| CONS2  _ -> "CONS2"
| CONS3  _ -> "CONS3"
| CONS4  _ -> "CONS4"
| DEFAULT  -> "DEFAULT"
| DIV  -> "DIV"
| DOLLAR  -> "DOLLAR"
| DOT  -> "DOT"
| DOUBLEQUOTE  -> "DOUBLEQUOTE"
| ELIST  _ -> "ELIST"
| EMPTY_TOKEN  -> "EMPTY_TOKEN"
| END  -> "END"
| EOF_TOKEN  -> "EOF_TOKEN"
| EQ  -> "EQ"
| ERROR  -> "ERROR"
| ERROR_TOKEN  -> "ERROR_TOKEN"
| GREATER  -> "GREATER"
| HASH  -> "HASH"
| IDENT  _ -> "IDENT"
| KW_DEFINE  -> "KW_DEFINE"
| KW_DEFINE_GROUP  -> "KW_DEFINE_GROUP"
| KW_FALSE  -> "KW_FALSE"
| KW_TRUE  -> "KW_TRUE"
| LBRACE  -> "LBRACE"
| LBRACK  -> "LBRACK"
| LCURLY  -> "LCURLY"
| LESS  -> "LESS"
| LINEFEED  -> "LINEFEED"
| LPAR  -> "LPAR"
| MINUS  -> "MINUS"
| MULT  -> "MULT"
| NUM  _ -> "NUM"
| PERCENT  -> "PERCENT"
| PLING  -> "PLING"
| PLUS  -> "PLUS"
| QUERY  -> "QUERY"
| QUOTE  -> "QUOTE"
| RBRACE  -> "RBRACE"
| RBRACK  -> "RBRACK"
| RCURLY  -> "RCURLY"
| RPAR  -> "RPAR"
| SEMI  -> "SEMI"
| SLIST  _ -> "SLIST"
| STRING  _ -> "STRING"
| TILDE  -> "TILDE"
| TLIST  _ -> "TLIST"
| TUPLE10  _ -> "TUPLE10"
| TUPLE2  _ -> "TUPLE2"
| TUPLE3  _ -> "TUPLE3"
| TUPLE4  _ -> "TUPLE4"
| TUPLE5  _ -> "TUPLE5"
| TUPLE6  _ -> "TUPLE6"
| TUPLE7  _ -> "TUPLE7"
| TUPLE8  _ -> "TUPLE8"
| TUPLE9  _ -> "TUPLE9"
| UNARY  -> "UNARY"
| UNDERSCORE  -> "UNDERSCORE"
| VBAR  -> "VBAR"

let (typehash:(string,unit)Hashtbl.t) = Hashtbl.create 257

let (packhash:(string,unit)Hashtbl.t) = Hashtbl.create 257
