dofile("library.lua")

print("Hello".."UHDM/Verilator")
v = Sys.arg(2)
w = Sys.arg(3)

lib=readlib()
ver=uhdm_parse(v)
rev=convert(map(lib,ver))
goldxml=verilator_parse(lib,w)
gold=convert(map(lib,goldxml))
z3sat(gold,rev)
minisat(gold,rev)
gatemap(ver)
print(itms.itm())
