always_example:
	ocamlfind ocamlc -o $@ -package base,hardcaml,hardcaml_waveterm -linkpkg always_example.ml

always_example_top:
	ocamlfind ocamlmktop -o $@ -package base,hardcaml,hardcaml_waveterm -linkpkg always_example.ml
